const PROPS_DATA = [
  {
    id: 1,
    title: "2-Bed Apartment — Ruaka",
    type: "Apartment",
    category: "rent",
    location: "Ruaka",
    price: 35000,
    beds: 2,
    baths: 1,
    sqft: 950,
    featured: true,
    desc: "Spacious 2-bedroom apartment near Quickmart, fitted kitchen and balcony. Secure compound with 24/7 security.",
    amenities: ["WiFi", "Parking", "Security", "Gym", "Balcony"],
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-1.pdf",
  },
  {
    id: 2,
    title: "3-Bed Villa — Limuru Road",
    type: "House",
    category: "sale",
    location: "Limuru Road",
    price: 12000000,
    beds: 3,
    baths: 2,
    sqft: 1800,
    featured: true,
    desc: "Modern 3-bedroom villa with garden and garage. Gated community with excellent security and amenities.",
    amenities: ["Garden", "Garage", "Security", "Gate", "Water Tank"],
    image:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-2.pdf",
  },
  {
    id: 3,
    title: "Office Space — Ruaraka",
    type: "Commercial",
    category: "sale",
    location: "Ruaraka",
    price: 200000,
    beds: 0,
    baths: 1,
    sqft: 2500,
    featured: false,
    desc: "Open-plan commercial office space with parking and high foot traffic. Ideal for business ventures.",
    amenities: ["Parking", "Security", "WiFi", "Reception"],
    image:
      "https://images.unsplash.com/photo-1497366216548-37519c721f3d?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-3.pdf",
  },
  {
    id: 4,
    title: "1-Bed Studio — Kiambu",
    type: "Apartment",
    category: "rent",
    location: "Kiambu",
    price: 22000,
    beds: 1,
    baths: 1,
    sqft: 450,
    featured: false,
    desc: "Cozy studio close to transport and amenities. Perfect for students or working professionals.",
    amenities: ["WiFi", "Water", "Gym", "Parking"],
    image:
      "https://images.unsplash.com/photo-1545324418-cc1ee142d993?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-4.pdf",
  },
  {
    id: 5,
    title: "4-Bed Townhouse — Nairobi",
    type: "House",
    category: "sale",
    location: "Nairobi",
    price: 120000000,
    beds: 4,
    baths: 3,
    sqft: 2200,
    featured: false,
    desc: "Townhouse in a gated community with security. Spacious and well-maintained with excellent facilities.",
    amenities: ["Gated community", "Security", "Garden", "Club House", "Gym"],
    image:
      "https://images.unsplash.com/photo-1570129477492-45c003d96c2c?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-5.pdf",
  },
  {
    id: 6,
    title: "Studio — Ruaka",
    type: "Apartment",
    category: "rent",
    location: "Ruaka",
    price: 12000,
    beds: 0,
    baths: 1,
    sqft: 250,
    featured: true,
    desc: "Affordable studio suitable for students and single occupants. Basic amenities and safe location.",
    amenities: ["WiFi", "Water", "Parking", "Security"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-6.pdf",
  },
  {
    id: 7,
    title: "2-Bed Apartment — Limuru Road",
    type: "Apartment",
    category: "rent",
    location: "Limuru Road",
    price: 42000,
    beds: 2,
    baths: 1,
    sqft: 1000,
    featured: false,
    desc: "Modern 2-bedroom apartment with fitted kitchen and hot water. Located near shopping centers and hospitals.",
    amenities: ["WiFi", "Hot Water", "Balcony", "Parking"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-7.pdf",
  },
  {
    id: 8,
    title: "3-Bed House — Ruaka Town",
    type: "House",
    category: "rent",
    location: "Ruaka",
    price: 75000,
    beds: 3,
    baths: 2,
    sqft: 1500,
    featured: false,
    desc: "Well-maintained 3-bedroom house with compound. Perfect for families. Secure neighborhood with good schools.",
    amenities: ["Compound", "Security", "Borehole", "Parking"],
    image:
      "https://images.unsplash.com/photo-1506317042271-5bcfba3e0ac9?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-8.pdf",
  },
  {
    id: 9,
    title: "2-Bed Villa — Limuru",
    type: "House",
    category: "sale",
    location: "Limuru",
    price: 8500000,
    beds: 2,
    baths: 2,
    sqft: 3000,
    featured: false,
    desc: "Beautiful 2-bedroom villa on 0.5 acre land. Modern amenities, and excellent investment.",
    amenities: ["Land", "Pool", "Garden", "Modern", "Security"],
    image:
      "https://images.unsplash.com/photo-1585399656776-d6a3f8b6bcd9?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-9.pdf",
  },
  {
    id: 10,
    title: "Retail Shop — Ruaraka",
    type: "Commercial",
    category: "rent",
    location: "Ruaraka",
    price: 45000,
    beds: 0,
    baths: 1,
    sqft: 800,
    featured: false,
    desc: "Prime retail shop space on main road with high visibility and foot traffic. Great for retail business.",
    amenities: ["Main Road", "Parking", "Security", "WiFi"],
    image:
      "https://images.unsplash.com/photo-1555636222-cae831e670b5?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-10.pdf",
  },
  {
    id: 11,
    title: "1-Bed Apartment — Kiambu Road",
    type: "Apartment",
    category: "rent",
    location: "Kiambu",
    price: 18000,
    beds: 1,
    baths: 1,
    sqft: 500,
    featured: false,
    desc: "Compact 1-bedroom apartment. Modern finishes, clean and secure. Ideal for young professionals.",
    amenities: ["Modern", "24hr surveilance", "WiFi", "Parking"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-11.pdf",
  },
  {
    id: 12,
    title: "5-Bed Bungalow — Karen",
    type: "House",
    category: "sale",
    location: "Karen",
    price: 65000000,
    beds: 5,
    baths: 4,
    sqft: 5000,
    featured: false,
    desc: "Luxury 5-bedroom bungalow in prestigious Karen. Swimming pool, gym, and gated security with 24/7 guards.",
    amenities: ["Pool", "Gym", "Guards", "Luxury"],
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56470?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-12.pdf",
  },
  {
    id: 13,
    title: "Warehouse — Industrial Area",
    type: "Commercial",
    category: "sale",
    location: "Industrial Area",
    price: 15000000,
    beds: 0,
    baths: 2,
    sqft: 8000,
    featured: false,
    desc: "Large warehouse space suitable for storage, manufacturing, or business operations. Excellent logistics location.",
    amenities: [
      "Loading Bay",
      "High Ceiling",
      "Parking",
      "Security",
      "Logistics",
    ],
    image:
      "https://images.unsplash.com/photo-1553531088-e57e3cc0e4c0?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-13.pdf",
  },
  {
    id: 14,
    title: "Studio — Limuru Road",
    type: "Apartment",
    category: "rent",
    location: "Limuru Road",
    price: 10000,
    beds: 0,
    baths: 1,
    sqft: 220,
    featured: false,
    desc: "Budget-friendly studio with basic amenities. Close to public transport and shopping centers.",
    amenities: ["Balcony", "Water", "Dstv"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-14.pdf",
  },
  {
    id: 15,
    title: "Office Suite — Westlands",
    type: "Commercial",
    category: "rent",
    location: "Westlands",
    price: 150000,
    beds: 0,
    baths: 2,
    sqft: 1500,
    featured: false,
    desc: "Serviced office suite with modern facilities, high-speed internet, and professional environment.",
    amenities: ["WiFi", "Reception", "Parking", "A/C", "Security"],
    image:
      "https://images.unsplash.com/photo-1497366216548-37519c721f3d?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-15.pdf",
  },
  {
    id: 16,
    title: "3-Bed Townhouse — Kileleshwa",
    type: "House",
    category: "sale",
    location: "Kileleshwa",
    price: 42000000,
    beds: 3,
    baths: 2,
    sqft: 2000,
    featured: false,
    desc: "Elegant 3-bedroom townhouse with modern design. Gated community with excellent amenities and security.",
    amenities: ["Modern", "Parking", "Security", "Gym"],
    image:
      "https://images.unsplash.com/photo-1570129477492-45c003d96c2c?w=600&h=400&fit=crop",
    virtualTour: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "brochures/property-16.pdf",
  },
  {
    id: 17,
    title: "1-Bed Apartment — Ruaka Central",
    type: "Apartment",
    category: "rent",
    location: "Ruaka",
    price: 25000,
    beds: 1,
    baths: 1,
    sqft: 550,
    featured: false,
    desc: "Centrally located 1-bedroom apartment. Walking distance to shops, clinics, and entertainment centers.",
    amenities: ["Elevetor", "WiFi", "Parking", "Water"],
    image:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-17.pdf",
  },
  {
    id: 18,
    title: "2-Bed Commercial Suite — Limuru",
    type: "Commercial",
    category: "rent",
    location: "Limuru",
    price: 60000,
    beds: 0,
    baths: 1,
    sqft: 1200,
    featured: false,
    desc: "Spacious commercial suite perfect for offices or professional services. Modern facilities and parking.",
    amenities: ["Modern", "Parking", "WiFi", "A/C", "Reception"],
    image:
      "https://images.unsplash.com/photo-1497366216548-37519c721f3d?w=600&h=400&fit=crop",
    virtualTour: "",
    brochure: "brochures/property-18.pdf",
  },
];
/* Make PROPS_DATA available to script.js */
